### ISSUE TITLE
test5 - i4 should be 7, not 5

### ISSUE THREAD

**Issue by hurda21** [spar36/SoftwareDev2020-A1#11]
Line 181: "TEST(arr.get(1) == arr.get(3)"

arr.get(1) is 7 after removing the second element. So i4 should also be 7 to pass the final test in that function.

**Comment by hurda21** [comment]
Same thing for floats: f4 should be 7.0f, not 5.7f

**Comment by hurda21** [comment]
Line 306: a1.to_string() should be a2->to_string()

**Comment by hurda21** [comment]
Line 336: a1.to_string() should be a2->to_string()

**Comment by hurda21** [comment]
Same for Line 364

**Comment by hurda21** [comment]
Same for Line 393.
Also the Line right before (392), a2->count() == 4, not 3

**Comment by evelynmawrey** [comment]
These should do it 94a08c8 5c6fac2
