### ISSUE TITLE
Making the API/Tests for Float, Integer and Boolean. 

### ISSUE THREAD

**Issue by wakira765** [spar36/SoftwareDev2020-A1#2]
Would you guys be able to write an interface for IntArray, FloatArray and BoolArray and the tests for them.
With what we have now we can only implement StrArray. 
Thanks!

**Comment by spar36** [comment]
added the specs in 90b6696
 will update tests to match soon

**Comment by evelynmawrey** [comment]
added tests in d934e49

**Comment by wakira765** [comment]
Thanks!
