### ISSUE TITLE
Adding to API: add and addAll functions to interface

### ISSUE THREAD

**Issue by wakira765** [spar36/SoftwareDev2020-A1#3]
Would you guys be able to add :
add() and addAll(Array *arr) to the interface? This is for some efficiency reasons in our implementation.

**Comment by evelynmawrey** [comment]
Would the functionality of add be equivalent to push_back per #6?
We can also add a push_back_all method as a complement.

**Comment by wakira765** [comment]
Yea they would have the same functionality. 
push_back and push_back_all works for me.

**Comment by evelynmawrey** [comment]
Spec added in 330e408, tests forthcoming

**Comment by evelynmawrey** [comment]
Tests added in c7905fb
