### ISSUE TITLE
Coherent String.h and Object.h

### ISSUE THREAD

**Issue by edchrepo** [spar36/SoftwareDev2020-A1#4]
In order for us and other teams to implement all 3 classes including your queue class, I think it's best to have a standardized object and string interface.

Most people in piazza are using this standardized object.h and string.h:
https://piazza.com/class/k51bluky59n2jr?cid=345

Though I like your object and string h interfaces, I was wondering if you could change it to those.

**Comment by evelynmawrey** [comment]
I think this is fine. Simpler than the Vitek version. Thoughts @spar36?

**Comment by wakira765** [comment]
This would be helpful for our group too!

**Comment by evelynmawrey** [comment]
Done in 6120ee8
