### ISSUE TITLE
Dynamic Array vs. Static Array

### ISSUE THREAD

**Issue by hurda21** [spar36/SoftwareDev2020-A1#5]
The assignment specs say that the array should grow in value when we add something bigger than the capacity. However, your comments indicate that you just want to implement a static array.

Could you change the description of your functions and add/change some test cases that cover adding values outside of capacity?

**Comment by hurda21** [comment]
Also, since they asked for dynamic, there should be a constructor that doesn't take in a size (since it'll automatically size according to what objects you add in or if you don't add anything on construction).

**Comment by evelynmawrey** [comment]
Should be solved with your PR #7. Let me know if I've misunderstood. Test cases will come shortly.

**Comment by hurda21** [comment]
Great! Looks good to me.

**Comment by evelynmawrey** [comment]
Tests added in c7905fb
